### ISSUE TITLE
Create new paths 

### ISSUE THREAD

**Issue by hovanter** [hovanter/footsteps#25]
1. Make the paths smaller. Alternatively, make the paths more horizontal to fit in screen
2. Make the paths start nearby each other at the Atrium
3. Paths should not overlap or be too close
4. Make the paths different colors (I think we should do this)

**Comment by hovanter** [comment]
^ Check the comment

**Comment by bhnascar** [comment]
^ Almost done, there's a mapbox layer glitch, hopefully it's a server side issue. Will revisit in a few hours.

**Comment by bhnascar** [comment]
Done. Problem was that lat/lng coordinates were off by 360.
